import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Providers } from "@/redux/Providers";
import { Toaster } from "@/components/ui/sonner";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className={cn(
          "relative h-full font-sans antialiased",
           inter.className
        )}>
          <main className="relative flex flex-col min-h-screen">
            <div className="flex-grow flex-1"> 
              <Providers>
                {children}
              </Providers>
            </div>
          </main>

          <Toaster />

      </body>
    </html>
  );
}
